### ISSUE TITLE
Wont compile with gowin due to new GW2A-18

### ISSUE THREAD

**Issue by stingpie** [YosysHQ/nextpnr#1185]
following instructions on windows 10 from https://learn.lushaylabs.com/os-toolchain-manual-installation/ caused an error on compilation. Two main issues: the "chipdb-GW2A-18.bba" was being named "chipdb-GW2A-18.bba.new", and once I renamed it, I got this error:
`bbasm: /home/stingpie/nextpnr/bba/main.cc:251: int main(int, char**): Assertion `!streams.empty()' failed.`
I fixed it by just commenting out line 251.

**Comment by yrabbit** [comment]
There should be no need to rename this file because this thing is done automatically at build time.
Something is wrong with the build system, maybe your apicula version is not 0.8.2a1 ?
Unfortunately this is all I can help - I do not have windows and can not repeat:(
![bba](https://github.com/YosysHQ/nextpnr/assets/6075465/9b44283b-c11b-4228-959a-8d0ecf1b5d56)
