### ISSUE TITLE
Speed up placer by performing incremental cost updates

### ISSUE THREAD

**Issue by eddiehung** [YosysHQ/nextpnr#50]
Based on [this profile](https://github.com/YosysHQ/nextpnr/files/2276516/design03.pdf) it appears that 86% of total runtime is spent inside placement, and 47% of total runtime is spent inside `get_net_metric()` which is responsible for computing the cost of a swap.

Instead of computing the half-perimeter-wire-length (HPWL) and worst-slack from scratch for every pin of every net of every affected cell, perhaps an incremental update can be performed? For example:
- if a pin is moved entirely inside the existing HPWL, then there's no need to recompute scratch
- if a pin does not currently have the worst-slack of the net, and does not increase the worst-slack, then no need to recompute from scratch
- etc.

**Comment by daveshah1** [comment]
#219 adds initial incremental bounding box computation (as placer1 performance is important to fast post-HeAP refinement) and #263 improves it further by considering more cases where a full update isn't needed. The placer now uses per-arc criticality/slack rather than worst slack in its timing model, so incremental slack updates would be more complicated.

**Comment by gatecat** [comment]
closing as the above mentioned fixes now cover most of this
