### ISSUE TITLE
-DSTATIC_BUILD=ON fails trying to link libpython3.6m.so

### ISSUE THREAD

**Issue by mithro** [YosysHQ/nextpnr#75]
Command line I'm using is;
`cmake -DARCH=ice40 -DBUILD_GUI=OFF -DSTATIC_BUILD=ON -DICEBOX_ROOT=${PREFIX}/share/icebox .`

Revision 474aa3470abb9a9bbbae137574542a6e5ac190a0

```
/home/tansell/conda/conda-bld/nextpnr_1537154254666/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: attempted static link of dynamic object `/home/tansell/conda/conda-bld/nextpnr_1537154254666/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/libpython3.6m.so'
```

**Comment by mmicko** [comment]
Problem with minimal CMake we are supporting (3.5 from Ubuntu 16.04) does not have support for hint to find only static library for Python, so static builds works only if you use : -DBUILD_PYTHON=OFF

**Comment by mithro** [comment]
So need a newer cmake?

**Comment by mmicko** [comment]
Well it would also require changes in CMakeList.txt to support new Cmake and set a proper hint. Also detecting python libs is done in different way in new version (they still support old style) so supporting this would probably break other builds. So guess for now just build it with  -DBUILD_PYTHON=OFF since for python builds to work on other machine would also require all python system libraries (from version of python that you linked it with), and it would hardly work on other machines.

**Comment by mmicko** [comment]
Fixed by https://github.com/YosysHQ/nextpnr/pull/325
