### ISSUE TITLE
FPGA feature licensing?

### ISSUE THREAD

**Issue by lukego** [YosysHQ/nextpnr#91]
How (if at all) will using an open source toolchain impact the licensing of FPGA features?

For a specific example, will it be necessary to pay for a license to use the SerDes capability of ECP5/ECP5-5G family chips?

I believe I read that some of these features have to be licensed separately and I am not sure if that is a license to enable the silicon or to use the design tools.

**Comment by steveatinfincia** [comment]
Standard "I'm not a lawyer" disclaimer applies, but generally if you bought or otherwise **own** a specific physical item, did not agree to any sort of contract or accept any sort of license agreement (whether in writing, signed, click-through, shrinkwrap, EULA, or otherwise), Lattice can't place *more* restrictions on what you can do with it, beyond what the law already restricts you from doing.

The laws that would *potentially* give Lattice the ability to demand licensing or payment in certain circumstances would be contract law, patent law, and copyright law.

My 2 cents: even if they did technically have a legal avenue to demand or enforce licensing for a particular feature, and I'm not sure they do, they may not care enough to do something about it. In this case "do something" would mean going to court, which is expensive. If anything they would probably have more of an issue with yosys itself, unless you're a large company.

### Contract law

If you haven't entered in to a contract or agreement of any kind with Lattice at any time, then you don't have any contractual obligations at all, and certainly haven't agreed to pay them for something.

If you **have**, you should read the agreement carefully. For example, if you've ever clicked through a license to use Lattice Diamond, you may very well have agreed not to use some particular feature without licensing or paying for it. But even if you do violate that agreement, the agreement itself is going to state what the consequences are, and if just says "you can't use Diamond anymore", you may or may not care.

### Patent law

Companies sometimes try to use patent law to claim they can dictate how an item can be used after it is sold, whether it can be resold to another party, or to claim that licensing is required in order to actually use it in a particular way or at all.

However, the legal concept of "patent exhaustion" means that once a specific ECP5 chip was sold, their *patent* rights over any patented inventions inside *that specific chip* were "exhausted" by the sale, and can no longer be used to exert control over it. 

So at least as far as patent law is concerned, that specific chip is yours, and you are free to use it however you wish within the bounds of the law, sell it to another entity without asking Lattice for permission, or destroy it.

If however you somehow find yourself in a situation where you specifically require a *patent license* from Lattice, for example because you're manufacturing ICs using something they have a patent on, you would end up having to sign a contract with them and they could require additional licensing of anything at that point.

### Copyright law

Copyright is a little more complicated, but is still subject to an "exhaustion rule" (the first sale doctrine), and generally copyright law only restricts actions that are related to copying/reproducing/distributing/selling a particular copy of a copyrighted work.

Once a particular copy of a copyrighted work, affixed in some physical "thing" like a DVD or a chip, is legitimately obtained from the copyright holder as a "first sale", whether in exchange for money or freely given to you, the copyright holder can no longer use the fact that the physical item 
you obtained from them contains a copyrighted work to dictate whether it can be resold, or whether you can use it without requiring a license from them.

Copyright wouldn't even apply if there isn't anything inside the chip that Lattice can claim they hold a copyright on, but I don't know if that's the case or not, and companies sometimes do stretch the meaning of "copyrighted work" until and unless a court rejects their argument.

### DMCA

The DMCA complicates things a little more, *if* Lattice can convince a court that there is a mechanism inside the chip that meets the DMCA definition of something that "effectively controls access" to a copyrighted work inside the chip itself, *and* convince a court that yosys or another tool is "circumventing" that access control mechanism, then they may have a case, and you would want to be very careful about how you proceed, and definitely consult an actual lawyer about it.
